java Triangle.Compiler tests/arrAccContextualErrorModoGet.tri
java Triangle.Compiler tests/arrAccContextualErrorModoPutint.tri
java Triangle.Compiler tests/arrAccContextualErrorNParamsGet.tri
java Triangle.Compiler tests/arrAccContextualErrorTipoPutint.tri
java Triangle.Compiler tests/arrAccContextualOKEjecMal.tri
java Triangle.Compiler tests/constErr01.tri
java Triangle.Compiler tests/constErrDeclarationRepeat01.tri
java Triangle.Compiler tests/constErrMayusYMinus01.tri
java Triangle.Compiler tests/dirAccDeclaration01.tri
java Triangle.Compiler tests/dirAccErr01.tri
java Triangle.Compiler tests/expressionErr01.tri
java Triangle.Compiler tests/funcDeclaration01.tri
java Triangle.Compiler tests/funcDeclaration02.tri
java Triangle.Compiler tests/IfErrExpression01.tri
java Triangle.Compiler tests/IfErrExpression02.tri
java Triangle.Compiler tests/IfErrExpression03.tri
java Triangle.Compiler tests/IfErrExpression04.tri
java Triangle.Compiler tests/IfErrExpression05.tri
java Triangle.Compiler tests/noDeclaractionErr01.tri
java Triangle.Compiler tests/noDeclaractionErr02.tri
java Triangle.Compiler tests/procErrConstParamVar01.tri
java Triangle.Compiler tests/procErrConstParamVar02.tri
java Triangle.Compiler tests/procErrConstParamVar03.tri
java Triangle.Compiler tests/procErrDesconocido.tri
java Triangle.Compiler tests/procErrFuncParam01.tri
java Triangle.Compiler tests/procErrFuncParam02.tri
java Triangle.Compiler tests/procErrNumParams01.tri
java Triangle.Compiler tests/procErrNumParams02.tri
java Triangle.Compiler tests/procErrParamInvisible.tri
java Triangle.Compiler tests/procErrParamsRepet01.tri
java Triangle.Compiler tests/procErrProcParam01.tri
java Triangle.Compiler tests/procErrProcParam02.tri
java Triangle.Compiler tests/procErrTipoParam.tri
java Triangle.Compiler tests/procErrTipoParam01.tri
java Triangle.Compiler tests/procOKFuncParam01.tri
java Triangle.Compiler tests/procOKParam.tri
java Triangle.Compiler tests/varAssign.tri
java Triangle.Compiler tests/varErrAssign.tri
java Triangle.Compiler tests/whileErrExpression01.tri
java Triangle.Compiler tests/whileErrExpression02.tri